apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv150
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/env/test150
    type: DirectoryOrCreate
  storageClassName: local-storage
  volumeMode: Filesystem
