elasticsearch:
  curator:
    enabled: true
  image:
    repository: sergbs/elastic
    tag: latest
  volumePermissions:
    enabled: true
  master:
    resources:
      requests: {}
  data:
    resources:
      requests: {}

kibana:
  image:
    repository: sergbs/kibana
    tag: latest
  extraConfiguration:
    elasticsearch.username: "kibanaserver"
    elasticsearch.password: "kibanaserver"
    elasticsearch.ssl.verificationMode: certificate
    elasticsearch.ssl.certificateAuthorities: "/opt/bitnami/kibana/certificates/root-ca.pem"
    opendistro_security.auth.type: "basicauth"
    opendistro_security.basicauth.forbidden_usernames: ["kibanaserver", "logstash"]
    server.ssl.enabled: true
    server.ssl.key: "/opt/bitnami/kibana/certificates/esnode-key.pem"
    server.ssl.certificate: "/opt/bitnami/kibana/certificates/esnode.pem"
    opendistro_security.accountinfo.enabled: true
  volumePermissions:
    enabled: true
  elasticsearch:
    hosts:
    - "efk-elasticsearch-coordinating-only"
    port: 9200
    tls: true
  ingress:
    enabled: true
    hosts:
      - name: kibana.local
        path: /
fluentd:
  enabled: false
  aggregator:
    enabled: false
    configMap: elasticsearch-output
    service:
      type: NodePort
    extraEnv:
    - name: ELASTICSEARCH_HOST
      value: "efk-elasticsearch-coordinating-only"
    - name: ELASTICSEARCH_PORT
      value: "9200"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
  forwarder:
#    Чтение логов с диска /var/log/containers/* отключено
    enabled: false
    resources:
      limits:
         cpu: 500m
         memory: 1Gi
    configMap: apache-log-parser
    extraEnv:
    - name: FLUENTD_DAEMON_USER
      value: root
    - name: FLUENTD_DAEMON_GROUP
      value: root
