apiVersion: v1
kind: Secret
metadata:
  name: opendistro-config
type: Opaque
data:
{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "files/*" }}
{{ base $path | indent 2 }}: '{{ $root.Files.Get $path | b64enc }}'
{{- end }}